DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS pagamentos CASCADE;
DROP TABLE IF EXISTS itens_venda CASCADE;
DROP TABLE IF EXISTS vendas CASCADE;
DROP TABLE IF EXISTS caixa CASCADE;
DROP TABLE IF EXISTS produtos CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS assinaturas CASCADE;
DROP TABLE IF EXISTS planos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS empresas CASCADE;
DROP FUNCTION IF EXISTS handle_new_user CASCADE;
DROP FUNCTION IF EXISTS check_produto_limit CASCADE;
DROP FUNCTION IF EXISTS check_venda_limit CASCADE;
DROP FUNCTION IF EXISTS update_updated_at CASCADE;
DROP FUNCTION IF EXISTS criar_venda CASCADE;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users CASCADE;
DROP TRIGGER IF EXISTS check_produto_limit_trigger ON produtos CASCADE;
DROP TRIGGER IF EXISTS check_venda_limit_trigger ON vendas CASCADE;
DROP TRIGGER IF EXISTS update_empresas_updated_at ON empresas CASCADE;
DROP TRIGGER IF EXISTS update_usuarios_updated_at ON usuarios CASCADE;
DROP TRIGGER IF EXISTS update_produtos_updated_at ON produtos CASCADE;
DROP TRIGGER IF EXISTS update_vendas_updated_at ON vendas CASCADE;
DROP TRIGGER IF EXISTS update_assinaturas_updated_at ON assinaturas CASCADE;
DROP TRIGGER IF EXISTS update_pagamentos_updated_at ON pagamentos CASCADE;
DROP TRIGGER IF EXISTS update_caixa_updated_at ON caixa CASCADE;
